directories:
  db_path: "data/chatbot.db"
  vectordb_dir: "data/vectordb"

llm_config:
  chat_model: "gpt-4o-mini"
  summary_model: "gpt-3.5-turbo"
  rag_model: "gpt-4o-mini"
  temperature: 0.0

search_config:
  num_retrieved_content: 3

chat_history_config:
  max_history_pairs: 2
  max_characters: 1000
  max_tokens: 2000

agent_config:
  max_function_calls: 3

vectordb_config:
  collection_name: "chat_history"
  embedding_model: "text-embedding-3-small" 
  k: 3